/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V1alpha1InfoItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1InfoItem{}

// V1alpha1InfoItem struct for V1alpha1InfoItem
type V1alpha1InfoItem struct {
	// Name is a human readable title for this piece of information.
	Name *string `json:"name,omitempty"`
	// Value is human readable content.
	Value *string `json:"value,omitempty"`
}

// NewV1alpha1InfoItem instantiates a new V1alpha1InfoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1InfoItem() *V1alpha1InfoItem {
	this := V1alpha1InfoItem{}
	return &this
}

// NewV1alpha1InfoItemWithDefaults instantiates a new V1alpha1InfoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1InfoItemWithDefaults() *V1alpha1InfoItem {
	this := V1alpha1InfoItem{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1alpha1InfoItem) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1InfoItem) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1alpha1InfoItem) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1alpha1InfoItem) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *V1alpha1InfoItem) GetValue() string {
	if o == nil || isNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1InfoItem) GetValueOk() (*string, bool) {
	if o == nil || isNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *V1alpha1InfoItem) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *V1alpha1InfoItem) SetValue(v string) {
	o.Value = &v
}

func (o V1alpha1InfoItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1InfoItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableV1alpha1InfoItem struct {
	value *V1alpha1InfoItem
	isSet bool
}

func (v NullableV1alpha1InfoItem) Get() *V1alpha1InfoItem {
	return v.value
}

func (v *NullableV1alpha1InfoItem) Set(val *V1alpha1InfoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1InfoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1InfoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1InfoItem(val *V1alpha1InfoItem) *NullableV1alpha1InfoItem {
	return &NullableV1alpha1InfoItem{value: val, isSet: true}
}

func (v NullableV1alpha1InfoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1InfoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


