/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V1alpha1PullRequestGeneratorGitLab type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1PullRequestGeneratorGitLab{}

// V1alpha1PullRequestGeneratorGitLab PullRequestGeneratorGitLab defines connection info specific to GitLab.
type V1alpha1PullRequestGeneratorGitLab struct {
	// The GitLab API URL to talk to. If blank, uses https://gitlab.com/.
	Api *string `json:"api,omitempty"`
	Labels []string `json:"labels,omitempty"`
	// GitLab project to scan. Required.
	Project *string `json:"project,omitempty"`
	PullRequestState *string `json:"pullRequestState,omitempty"`
	TokenRef *V1alpha1SecretRef `json:"tokenRef,omitempty"`
}

// NewV1alpha1PullRequestGeneratorGitLab instantiates a new V1alpha1PullRequestGeneratorGitLab object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1PullRequestGeneratorGitLab() *V1alpha1PullRequestGeneratorGitLab {
	this := V1alpha1PullRequestGeneratorGitLab{}
	return &this
}

// NewV1alpha1PullRequestGeneratorGitLabWithDefaults instantiates a new V1alpha1PullRequestGeneratorGitLab object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1PullRequestGeneratorGitLabWithDefaults() *V1alpha1PullRequestGeneratorGitLab {
	this := V1alpha1PullRequestGeneratorGitLab{}
	return &this
}

// GetApi returns the Api field value if set, zero value otherwise.
func (o *V1alpha1PullRequestGeneratorGitLab) GetApi() string {
	if o == nil || isNil(o.Api) {
		var ret string
		return ret
	}
	return *o.Api
}

// GetApiOk returns a tuple with the Api field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) GetApiOk() (*string, bool) {
	if o == nil || isNil(o.Api) {
		return nil, false
	}
	return o.Api, true
}

// HasApi returns a boolean if a field has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) HasApi() bool {
	if o != nil && !isNil(o.Api) {
		return true
	}

	return false
}

// SetApi gets a reference to the given string and assigns it to the Api field.
func (o *V1alpha1PullRequestGeneratorGitLab) SetApi(v string) {
	o.Api = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *V1alpha1PullRequestGeneratorGitLab) GetLabels() []string {
	if o == nil || isNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) GetLabelsOk() ([]string, bool) {
	if o == nil || isNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) HasLabels() bool {
	if o != nil && !isNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *V1alpha1PullRequestGeneratorGitLab) SetLabels(v []string) {
	o.Labels = v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *V1alpha1PullRequestGeneratorGitLab) GetProject() string {
	if o == nil || isNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) GetProjectOk() (*string, bool) {
	if o == nil || isNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) HasProject() bool {
	if o != nil && !isNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *V1alpha1PullRequestGeneratorGitLab) SetProject(v string) {
	o.Project = &v
}

// GetPullRequestState returns the PullRequestState field value if set, zero value otherwise.
func (o *V1alpha1PullRequestGeneratorGitLab) GetPullRequestState() string {
	if o == nil || isNil(o.PullRequestState) {
		var ret string
		return ret
	}
	return *o.PullRequestState
}

// GetPullRequestStateOk returns a tuple with the PullRequestState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) GetPullRequestStateOk() (*string, bool) {
	if o == nil || isNil(o.PullRequestState) {
		return nil, false
	}
	return o.PullRequestState, true
}

// HasPullRequestState returns a boolean if a field has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) HasPullRequestState() bool {
	if o != nil && !isNil(o.PullRequestState) {
		return true
	}

	return false
}

// SetPullRequestState gets a reference to the given string and assigns it to the PullRequestState field.
func (o *V1alpha1PullRequestGeneratorGitLab) SetPullRequestState(v string) {
	o.PullRequestState = &v
}

// GetTokenRef returns the TokenRef field value if set, zero value otherwise.
func (o *V1alpha1PullRequestGeneratorGitLab) GetTokenRef() V1alpha1SecretRef {
	if o == nil || isNil(o.TokenRef) {
		var ret V1alpha1SecretRef
		return ret
	}
	return *o.TokenRef
}

// GetTokenRefOk returns a tuple with the TokenRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) GetTokenRefOk() (*V1alpha1SecretRef, bool) {
	if o == nil || isNil(o.TokenRef) {
		return nil, false
	}
	return o.TokenRef, true
}

// HasTokenRef returns a boolean if a field has been set.
func (o *V1alpha1PullRequestGeneratorGitLab) HasTokenRef() bool {
	if o != nil && !isNil(o.TokenRef) {
		return true
	}

	return false
}

// SetTokenRef gets a reference to the given V1alpha1SecretRef and assigns it to the TokenRef field.
func (o *V1alpha1PullRequestGeneratorGitLab) SetTokenRef(v V1alpha1SecretRef) {
	o.TokenRef = &v
}

func (o V1alpha1PullRequestGeneratorGitLab) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1PullRequestGeneratorGitLab) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Api) {
		toSerialize["api"] = o.Api
	}
	if !isNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !isNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !isNil(o.PullRequestState) {
		toSerialize["pullRequestState"] = o.PullRequestState
	}
	if !isNil(o.TokenRef) {
		toSerialize["tokenRef"] = o.TokenRef
	}
	return toSerialize, nil
}

type NullableV1alpha1PullRequestGeneratorGitLab struct {
	value *V1alpha1PullRequestGeneratorGitLab
	isSet bool
}

func (v NullableV1alpha1PullRequestGeneratorGitLab) Get() *V1alpha1PullRequestGeneratorGitLab {
	return v.value
}

func (v *NullableV1alpha1PullRequestGeneratorGitLab) Set(val *V1alpha1PullRequestGeneratorGitLab) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1PullRequestGeneratorGitLab) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1PullRequestGeneratorGitLab) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1PullRequestGeneratorGitLab(val *V1alpha1PullRequestGeneratorGitLab) *NullableV1alpha1PullRequestGeneratorGitLab {
	return &NullableV1alpha1PullRequestGeneratorGitLab{value: val, isSet: true}
}

func (v NullableV1alpha1PullRequestGeneratorGitLab) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1PullRequestGeneratorGitLab) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


