/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApplicationApplicationRollbackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationApplicationRollbackRequest{}

// ApplicationApplicationRollbackRequest struct for ApplicationApplicationRollbackRequest
type ApplicationApplicationRollbackRequest struct {
	AppNamespace *string `json:"appNamespace,omitempty"`
	DryRun *bool `json:"dryRun,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Prune *bool `json:"prune,omitempty"`
}

// NewApplicationApplicationRollbackRequest instantiates a new ApplicationApplicationRollbackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationApplicationRollbackRequest() *ApplicationApplicationRollbackRequest {
	this := ApplicationApplicationRollbackRequest{}
	return &this
}

// NewApplicationApplicationRollbackRequestWithDefaults instantiates a new ApplicationApplicationRollbackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationApplicationRollbackRequestWithDefaults() *ApplicationApplicationRollbackRequest {
	this := ApplicationApplicationRollbackRequest{}
	return &this
}

// GetAppNamespace returns the AppNamespace field value if set, zero value otherwise.
func (o *ApplicationApplicationRollbackRequest) GetAppNamespace() string {
	if o == nil || isNil(o.AppNamespace) {
		var ret string
		return ret
	}
	return *o.AppNamespace
}

// GetAppNamespaceOk returns a tuple with the AppNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationRollbackRequest) GetAppNamespaceOk() (*string, bool) {
	if o == nil || isNil(o.AppNamespace) {
		return nil, false
	}
	return o.AppNamespace, true
}

// HasAppNamespace returns a boolean if a field has been set.
func (o *ApplicationApplicationRollbackRequest) HasAppNamespace() bool {
	if o != nil && !isNil(o.AppNamespace) {
		return true
	}

	return false
}

// SetAppNamespace gets a reference to the given string and assigns it to the AppNamespace field.
func (o *ApplicationApplicationRollbackRequest) SetAppNamespace(v string) {
	o.AppNamespace = &v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *ApplicationApplicationRollbackRequest) GetDryRun() bool {
	if o == nil || isNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationRollbackRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || isNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *ApplicationApplicationRollbackRequest) HasDryRun() bool {
	if o != nil && !isNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *ApplicationApplicationRollbackRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApplicationApplicationRollbackRequest) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationRollbackRequest) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApplicationApplicationRollbackRequest) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApplicationApplicationRollbackRequest) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationApplicationRollbackRequest) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationRollbackRequest) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationApplicationRollbackRequest) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationApplicationRollbackRequest) SetName(v string) {
	o.Name = &v
}

// GetPrune returns the Prune field value if set, zero value otherwise.
func (o *ApplicationApplicationRollbackRequest) GetPrune() bool {
	if o == nil || isNil(o.Prune) {
		var ret bool
		return ret
	}
	return *o.Prune
}

// GetPruneOk returns a tuple with the Prune field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationRollbackRequest) GetPruneOk() (*bool, bool) {
	if o == nil || isNil(o.Prune) {
		return nil, false
	}
	return o.Prune, true
}

// HasPrune returns a boolean if a field has been set.
func (o *ApplicationApplicationRollbackRequest) HasPrune() bool {
	if o != nil && !isNil(o.Prune) {
		return true
	}

	return false
}

// SetPrune gets a reference to the given bool and assigns it to the Prune field.
func (o *ApplicationApplicationRollbackRequest) SetPrune(v bool) {
	o.Prune = &v
}

func (o ApplicationApplicationRollbackRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationApplicationRollbackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AppNamespace) {
		toSerialize["appNamespace"] = o.AppNamespace
	}
	if !isNil(o.DryRun) {
		toSerialize["dryRun"] = o.DryRun
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Prune) {
		toSerialize["prune"] = o.Prune
	}
	return toSerialize, nil
}

type NullableApplicationApplicationRollbackRequest struct {
	value *ApplicationApplicationRollbackRequest
	isSet bool
}

func (v NullableApplicationApplicationRollbackRequest) Get() *ApplicationApplicationRollbackRequest {
	return v.value
}

func (v *NullableApplicationApplicationRollbackRequest) Set(val *ApplicationApplicationRollbackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationApplicationRollbackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationApplicationRollbackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationApplicationRollbackRequest(val *ApplicationApplicationRollbackRequest) *NullableApplicationApplicationRollbackRequest {
	return &NullableApplicationApplicationRollbackRequest{value: val, isSet: true}
}

func (v NullableApplicationApplicationRollbackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationApplicationRollbackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


