/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V1alpha1ApplicationSetSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1ApplicationSetSpec{}

// V1alpha1ApplicationSetSpec ApplicationSetSpec represents a class of application set state.
type V1alpha1ApplicationSetSpec struct {
	Generators []V1alpha1ApplicationSetGenerator `json:"generators,omitempty"`
	GoTemplate *bool `json:"goTemplate,omitempty"`
	SyncPolicy *V1alpha1ApplicationSetSyncPolicy `json:"syncPolicy,omitempty"`
	Template *V1alpha1ApplicationSetTemplate `json:"template,omitempty"`
}

// NewV1alpha1ApplicationSetSpec instantiates a new V1alpha1ApplicationSetSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1ApplicationSetSpec() *V1alpha1ApplicationSetSpec {
	this := V1alpha1ApplicationSetSpec{}
	return &this
}

// NewV1alpha1ApplicationSetSpecWithDefaults instantiates a new V1alpha1ApplicationSetSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1ApplicationSetSpecWithDefaults() *V1alpha1ApplicationSetSpec {
	this := V1alpha1ApplicationSetSpec{}
	return &this
}

// GetGenerators returns the Generators field value if set, zero value otherwise.
func (o *V1alpha1ApplicationSetSpec) GetGenerators() []V1alpha1ApplicationSetGenerator {
	if o == nil || isNil(o.Generators) {
		var ret []V1alpha1ApplicationSetGenerator
		return ret
	}
	return o.Generators
}

// GetGeneratorsOk returns a tuple with the Generators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ApplicationSetSpec) GetGeneratorsOk() ([]V1alpha1ApplicationSetGenerator, bool) {
	if o == nil || isNil(o.Generators) {
		return nil, false
	}
	return o.Generators, true
}

// HasGenerators returns a boolean if a field has been set.
func (o *V1alpha1ApplicationSetSpec) HasGenerators() bool {
	if o != nil && !isNil(o.Generators) {
		return true
	}

	return false
}

// SetGenerators gets a reference to the given []V1alpha1ApplicationSetGenerator and assigns it to the Generators field.
func (o *V1alpha1ApplicationSetSpec) SetGenerators(v []V1alpha1ApplicationSetGenerator) {
	o.Generators = v
}

// GetGoTemplate returns the GoTemplate field value if set, zero value otherwise.
func (o *V1alpha1ApplicationSetSpec) GetGoTemplate() bool {
	if o == nil || isNil(o.GoTemplate) {
		var ret bool
		return ret
	}
	return *o.GoTemplate
}

// GetGoTemplateOk returns a tuple with the GoTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ApplicationSetSpec) GetGoTemplateOk() (*bool, bool) {
	if o == nil || isNil(o.GoTemplate) {
		return nil, false
	}
	return o.GoTemplate, true
}

// HasGoTemplate returns a boolean if a field has been set.
func (o *V1alpha1ApplicationSetSpec) HasGoTemplate() bool {
	if o != nil && !isNil(o.GoTemplate) {
		return true
	}

	return false
}

// SetGoTemplate gets a reference to the given bool and assigns it to the GoTemplate field.
func (o *V1alpha1ApplicationSetSpec) SetGoTemplate(v bool) {
	o.GoTemplate = &v
}

// GetSyncPolicy returns the SyncPolicy field value if set, zero value otherwise.
func (o *V1alpha1ApplicationSetSpec) GetSyncPolicy() V1alpha1ApplicationSetSyncPolicy {
	if o == nil || isNil(o.SyncPolicy) {
		var ret V1alpha1ApplicationSetSyncPolicy
		return ret
	}
	return *o.SyncPolicy
}

// GetSyncPolicyOk returns a tuple with the SyncPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ApplicationSetSpec) GetSyncPolicyOk() (*V1alpha1ApplicationSetSyncPolicy, bool) {
	if o == nil || isNil(o.SyncPolicy) {
		return nil, false
	}
	return o.SyncPolicy, true
}

// HasSyncPolicy returns a boolean if a field has been set.
func (o *V1alpha1ApplicationSetSpec) HasSyncPolicy() bool {
	if o != nil && !isNil(o.SyncPolicy) {
		return true
	}

	return false
}

// SetSyncPolicy gets a reference to the given V1alpha1ApplicationSetSyncPolicy and assigns it to the SyncPolicy field.
func (o *V1alpha1ApplicationSetSpec) SetSyncPolicy(v V1alpha1ApplicationSetSyncPolicy) {
	o.SyncPolicy = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *V1alpha1ApplicationSetSpec) GetTemplate() V1alpha1ApplicationSetTemplate {
	if o == nil || isNil(o.Template) {
		var ret V1alpha1ApplicationSetTemplate
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ApplicationSetSpec) GetTemplateOk() (*V1alpha1ApplicationSetTemplate, bool) {
	if o == nil || isNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *V1alpha1ApplicationSetSpec) HasTemplate() bool {
	if o != nil && !isNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given V1alpha1ApplicationSetTemplate and assigns it to the Template field.
func (o *V1alpha1ApplicationSetSpec) SetTemplate(v V1alpha1ApplicationSetTemplate) {
	o.Template = &v
}

func (o V1alpha1ApplicationSetSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1ApplicationSetSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Generators) {
		toSerialize["generators"] = o.Generators
	}
	if !isNil(o.GoTemplate) {
		toSerialize["goTemplate"] = o.GoTemplate
	}
	if !isNil(o.SyncPolicy) {
		toSerialize["syncPolicy"] = o.SyncPolicy
	}
	if !isNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	return toSerialize, nil
}

type NullableV1alpha1ApplicationSetSpec struct {
	value *V1alpha1ApplicationSetSpec
	isSet bool
}

func (v NullableV1alpha1ApplicationSetSpec) Get() *V1alpha1ApplicationSetSpec {
	return v.value
}

func (v *NullableV1alpha1ApplicationSetSpec) Set(val *V1alpha1ApplicationSetSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1ApplicationSetSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1ApplicationSetSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1ApplicationSetSpec(val *V1alpha1ApplicationSetSpec) *NullableV1alpha1ApplicationSetSpec {
	return &NullableV1alpha1ApplicationSetSpec{value: val, isSet: true}
}

func (v NullableV1alpha1ApplicationSetSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1ApplicationSetSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


