/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the NotificationService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationService{}

// NotificationService struct for NotificationService
type NotificationService struct {
	Name *string `json:"name,omitempty"`
}

// NewNotificationService instantiates a new NotificationService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationService() *NotificationService {
	this := NotificationService{}
	return &this
}

// NewNotificationServiceWithDefaults instantiates a new NotificationService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationServiceWithDefaults() *NotificationService {
	this := NotificationService{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NotificationService) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationService) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NotificationService) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NotificationService) SetName(v string) {
	o.Name = &v
}

func (o NotificationService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableNotificationService struct {
	value *NotificationService
	isSet bool
}

func (v NullableNotificationService) Get() *NotificationService {
	return v.value
}

func (v *NullableNotificationService) Set(val *NotificationService) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationService) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationService(val *NotificationService) *NullableNotificationService {
	return &NullableNotificationService{value: val, isSet: true}
}

func (v NullableNotificationService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


