/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V1alpha1GitFileGeneratorItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1GitFileGeneratorItem{}

// V1alpha1GitFileGeneratorItem struct for V1alpha1GitFileGeneratorItem
type V1alpha1GitFileGeneratorItem struct {
	Path *string `json:"path,omitempty"`
}

// NewV1alpha1GitFileGeneratorItem instantiates a new V1alpha1GitFileGeneratorItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1GitFileGeneratorItem() *V1alpha1GitFileGeneratorItem {
	this := V1alpha1GitFileGeneratorItem{}
	return &this
}

// NewV1alpha1GitFileGeneratorItemWithDefaults instantiates a new V1alpha1GitFileGeneratorItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1GitFileGeneratorItemWithDefaults() *V1alpha1GitFileGeneratorItem {
	this := V1alpha1GitFileGeneratorItem{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *V1alpha1GitFileGeneratorItem) GetPath() string {
	if o == nil || isNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1GitFileGeneratorItem) GetPathOk() (*string, bool) {
	if o == nil || isNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *V1alpha1GitFileGeneratorItem) HasPath() bool {
	if o != nil && !isNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *V1alpha1GitFileGeneratorItem) SetPath(v string) {
	o.Path = &v
}

func (o V1alpha1GitFileGeneratorItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1GitFileGeneratorItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	return toSerialize, nil
}

type NullableV1alpha1GitFileGeneratorItem struct {
	value *V1alpha1GitFileGeneratorItem
	isSet bool
}

func (v NullableV1alpha1GitFileGeneratorItem) Get() *V1alpha1GitFileGeneratorItem {
	return v.value
}

func (v *NullableV1alpha1GitFileGeneratorItem) Set(val *V1alpha1GitFileGeneratorItem) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1GitFileGeneratorItem) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1GitFileGeneratorItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1GitFileGeneratorItem(val *V1alpha1GitFileGeneratorItem) *NullableV1alpha1GitFileGeneratorItem {
	return &NullableV1alpha1GitFileGeneratorItem{value: val, isSet: true}
}

func (v NullableV1alpha1GitFileGeneratorItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1GitFileGeneratorItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


