/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RepositoryRepoAppsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryRepoAppsResponse{}

// RepositoryRepoAppsResponse struct for RepositoryRepoAppsResponse
type RepositoryRepoAppsResponse struct {
	Items []RepositoryAppInfo `json:"items,omitempty"`
}

// NewRepositoryRepoAppsResponse instantiates a new RepositoryRepoAppsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryRepoAppsResponse() *RepositoryRepoAppsResponse {
	this := RepositoryRepoAppsResponse{}
	return &this
}

// NewRepositoryRepoAppsResponseWithDefaults instantiates a new RepositoryRepoAppsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryRepoAppsResponseWithDefaults() *RepositoryRepoAppsResponse {
	this := RepositoryRepoAppsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *RepositoryRepoAppsResponse) GetItems() []RepositoryAppInfo {
	if o == nil || isNil(o.Items) {
		var ret []RepositoryAppInfo
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRepoAppsResponse) GetItemsOk() ([]RepositoryAppInfo, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *RepositoryRepoAppsResponse) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []RepositoryAppInfo and assigns it to the Items field.
func (o *RepositoryRepoAppsResponse) SetItems(v []RepositoryAppInfo) {
	o.Items = v
}

func (o RepositoryRepoAppsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryRepoAppsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableRepositoryRepoAppsResponse struct {
	value *RepositoryRepoAppsResponse
	isSet bool
}

func (v NullableRepositoryRepoAppsResponse) Get() *RepositoryRepoAppsResponse {
	return v.value
}

func (v *NullableRepositoryRepoAppsResponse) Set(val *RepositoryRepoAppsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryRepoAppsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryRepoAppsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryRepoAppsResponse(val *RepositoryRepoAppsResponse) *NullableRepositoryRepoAppsResponse {
	return &NullableRepositoryRepoAppsResponse{value: val, isSet: true}
}

func (v NullableRepositoryRepoAppsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryRepoAppsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


