/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApplicationApplicationSyncWindowsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationApplicationSyncWindowsResponse{}

// ApplicationApplicationSyncWindowsResponse struct for ApplicationApplicationSyncWindowsResponse
type ApplicationApplicationSyncWindowsResponse struct {
	ActiveWindows []ApplicationApplicationSyncWindow `json:"activeWindows,omitempty"`
	AssignedWindows []ApplicationApplicationSyncWindow `json:"assignedWindows,omitempty"`
	CanSync *bool `json:"canSync,omitempty"`
}

// NewApplicationApplicationSyncWindowsResponse instantiates a new ApplicationApplicationSyncWindowsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationApplicationSyncWindowsResponse() *ApplicationApplicationSyncWindowsResponse {
	this := ApplicationApplicationSyncWindowsResponse{}
	return &this
}

// NewApplicationApplicationSyncWindowsResponseWithDefaults instantiates a new ApplicationApplicationSyncWindowsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationApplicationSyncWindowsResponseWithDefaults() *ApplicationApplicationSyncWindowsResponse {
	this := ApplicationApplicationSyncWindowsResponse{}
	return &this
}

// GetActiveWindows returns the ActiveWindows field value if set, zero value otherwise.
func (o *ApplicationApplicationSyncWindowsResponse) GetActiveWindows() []ApplicationApplicationSyncWindow {
	if o == nil || isNil(o.ActiveWindows) {
		var ret []ApplicationApplicationSyncWindow
		return ret
	}
	return o.ActiveWindows
}

// GetActiveWindowsOk returns a tuple with the ActiveWindows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationSyncWindowsResponse) GetActiveWindowsOk() ([]ApplicationApplicationSyncWindow, bool) {
	if o == nil || isNil(o.ActiveWindows) {
		return nil, false
	}
	return o.ActiveWindows, true
}

// HasActiveWindows returns a boolean if a field has been set.
func (o *ApplicationApplicationSyncWindowsResponse) HasActiveWindows() bool {
	if o != nil && !isNil(o.ActiveWindows) {
		return true
	}

	return false
}

// SetActiveWindows gets a reference to the given []ApplicationApplicationSyncWindow and assigns it to the ActiveWindows field.
func (o *ApplicationApplicationSyncWindowsResponse) SetActiveWindows(v []ApplicationApplicationSyncWindow) {
	o.ActiveWindows = v
}

// GetAssignedWindows returns the AssignedWindows field value if set, zero value otherwise.
func (o *ApplicationApplicationSyncWindowsResponse) GetAssignedWindows() []ApplicationApplicationSyncWindow {
	if o == nil || isNil(o.AssignedWindows) {
		var ret []ApplicationApplicationSyncWindow
		return ret
	}
	return o.AssignedWindows
}

// GetAssignedWindowsOk returns a tuple with the AssignedWindows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationSyncWindowsResponse) GetAssignedWindowsOk() ([]ApplicationApplicationSyncWindow, bool) {
	if o == nil || isNil(o.AssignedWindows) {
		return nil, false
	}
	return o.AssignedWindows, true
}

// HasAssignedWindows returns a boolean if a field has been set.
func (o *ApplicationApplicationSyncWindowsResponse) HasAssignedWindows() bool {
	if o != nil && !isNil(o.AssignedWindows) {
		return true
	}

	return false
}

// SetAssignedWindows gets a reference to the given []ApplicationApplicationSyncWindow and assigns it to the AssignedWindows field.
func (o *ApplicationApplicationSyncWindowsResponse) SetAssignedWindows(v []ApplicationApplicationSyncWindow) {
	o.AssignedWindows = v
}

// GetCanSync returns the CanSync field value if set, zero value otherwise.
func (o *ApplicationApplicationSyncWindowsResponse) GetCanSync() bool {
	if o == nil || isNil(o.CanSync) {
		var ret bool
		return ret
	}
	return *o.CanSync
}

// GetCanSyncOk returns a tuple with the CanSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationSyncWindowsResponse) GetCanSyncOk() (*bool, bool) {
	if o == nil || isNil(o.CanSync) {
		return nil, false
	}
	return o.CanSync, true
}

// HasCanSync returns a boolean if a field has been set.
func (o *ApplicationApplicationSyncWindowsResponse) HasCanSync() bool {
	if o != nil && !isNil(o.CanSync) {
		return true
	}

	return false
}

// SetCanSync gets a reference to the given bool and assigns it to the CanSync field.
func (o *ApplicationApplicationSyncWindowsResponse) SetCanSync(v bool) {
	o.CanSync = &v
}

func (o ApplicationApplicationSyncWindowsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationApplicationSyncWindowsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ActiveWindows) {
		toSerialize["activeWindows"] = o.ActiveWindows
	}
	if !isNil(o.AssignedWindows) {
		toSerialize["assignedWindows"] = o.AssignedWindows
	}
	if !isNil(o.CanSync) {
		toSerialize["canSync"] = o.CanSync
	}
	return toSerialize, nil
}

type NullableApplicationApplicationSyncWindowsResponse struct {
	value *ApplicationApplicationSyncWindowsResponse
	isSet bool
}

func (v NullableApplicationApplicationSyncWindowsResponse) Get() *ApplicationApplicationSyncWindowsResponse {
	return v.value
}

func (v *NullableApplicationApplicationSyncWindowsResponse) Set(val *ApplicationApplicationSyncWindowsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationApplicationSyncWindowsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationApplicationSyncWindowsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationApplicationSyncWindowsResponse(val *ApplicationApplicationSyncWindowsResponse) *NullableApplicationApplicationSyncWindowsResponse {
	return &NullableApplicationApplicationSyncWindowsResponse{value: val, isSet: true}
}

func (v NullableApplicationApplicationSyncWindowsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationApplicationSyncWindowsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


