/*
Consolidate Services

Testing RepoCredsServiceApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/eschercloudai/argocd-client-go/client"
)

func Test_client_RepoCredsServiceApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RepoCredsServiceApiService RepoCredsServiceCreateRepositoryCredentials", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RepoCredsServiceApi.RepoCredsServiceCreateRepositoryCredentials(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepoCredsServiceApiService RepoCredsServiceDeleteRepositoryCredentials", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var url string

		resp, httpRes, err := apiClient.RepoCredsServiceApi.RepoCredsServiceDeleteRepositoryCredentials(context.Background(), url).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepoCredsServiceApiService RepoCredsServiceListRepositoryCredentials", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RepoCredsServiceApi.RepoCredsServiceListRepositoryCredentials(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepoCredsServiceApiService RepoCredsServiceUpdateRepositoryCredentials", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var credsUrl string

		resp, httpRes, err := apiClient.RepoCredsServiceApi.RepoCredsServiceUpdateRepositoryCredentials(context.Background(), credsUrl).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
