/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the RepositoryRepoAppDetailsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryRepoAppDetailsResponse{}

// RepositoryRepoAppDetailsResponse struct for RepositoryRepoAppDetailsResponse
type RepositoryRepoAppDetailsResponse struct {
	Directory map[string]interface{}      `json:"directory,omitempty"`
	Helm      *RepositoryHelmAppSpec      `json:"helm,omitempty"`
	Kustomize *RepositoryKustomizeAppSpec `json:"kustomize,omitempty"`
	Type      *string                     `json:"type,omitempty"`
}

// NewRepositoryRepoAppDetailsResponse instantiates a new RepositoryRepoAppDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryRepoAppDetailsResponse() *RepositoryRepoAppDetailsResponse {
	this := RepositoryRepoAppDetailsResponse{}
	return &this
}

// NewRepositoryRepoAppDetailsResponseWithDefaults instantiates a new RepositoryRepoAppDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryRepoAppDetailsResponseWithDefaults() *RepositoryRepoAppDetailsResponse {
	this := RepositoryRepoAppDetailsResponse{}
	return &this
}

// GetDirectory returns the Directory field value if set, zero value otherwise.
func (o *RepositoryRepoAppDetailsResponse) GetDirectory() map[string]interface{} {
	if o == nil || isNil(o.Directory) {
		var ret map[string]interface{}
		return ret
	}
	return o.Directory
}

// GetDirectoryOk returns a tuple with the Directory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRepoAppDetailsResponse) GetDirectoryOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Directory) {
		return map[string]interface{}{}, false
	}
	return o.Directory, true
}

// HasDirectory returns a boolean if a field has been set.
func (o *RepositoryRepoAppDetailsResponse) HasDirectory() bool {
	if o != nil && !isNil(o.Directory) {
		return true
	}

	return false
}

// SetDirectory gets a reference to the given map[string]interface{} and assigns it to the Directory field.
func (o *RepositoryRepoAppDetailsResponse) SetDirectory(v map[string]interface{}) {
	o.Directory = v
}

// GetHelm returns the Helm field value if set, zero value otherwise.
func (o *RepositoryRepoAppDetailsResponse) GetHelm() RepositoryHelmAppSpec {
	if o == nil || isNil(o.Helm) {
		var ret RepositoryHelmAppSpec
		return ret
	}
	return *o.Helm
}

// GetHelmOk returns a tuple with the Helm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRepoAppDetailsResponse) GetHelmOk() (*RepositoryHelmAppSpec, bool) {
	if o == nil || isNil(o.Helm) {
		return nil, false
	}
	return o.Helm, true
}

// HasHelm returns a boolean if a field has been set.
func (o *RepositoryRepoAppDetailsResponse) HasHelm() bool {
	if o != nil && !isNil(o.Helm) {
		return true
	}

	return false
}

// SetHelm gets a reference to the given RepositoryHelmAppSpec and assigns it to the Helm field.
func (o *RepositoryRepoAppDetailsResponse) SetHelm(v RepositoryHelmAppSpec) {
	o.Helm = &v
}

// GetKustomize returns the Kustomize field value if set, zero value otherwise.
func (o *RepositoryRepoAppDetailsResponse) GetKustomize() RepositoryKustomizeAppSpec {
	if o == nil || isNil(o.Kustomize) {
		var ret RepositoryKustomizeAppSpec
		return ret
	}
	return *o.Kustomize
}

// GetKustomizeOk returns a tuple with the Kustomize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRepoAppDetailsResponse) GetKustomizeOk() (*RepositoryKustomizeAppSpec, bool) {
	if o == nil || isNil(o.Kustomize) {
		return nil, false
	}
	return o.Kustomize, true
}

// HasKustomize returns a boolean if a field has been set.
func (o *RepositoryRepoAppDetailsResponse) HasKustomize() bool {
	if o != nil && !isNil(o.Kustomize) {
		return true
	}

	return false
}

// SetKustomize gets a reference to the given RepositoryKustomizeAppSpec and assigns it to the Kustomize field.
func (o *RepositoryRepoAppDetailsResponse) SetKustomize(v RepositoryKustomizeAppSpec) {
	o.Kustomize = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RepositoryRepoAppDetailsResponse) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRepoAppDetailsResponse) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RepositoryRepoAppDetailsResponse) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RepositoryRepoAppDetailsResponse) SetType(v string) {
	o.Type = &v
}

func (o RepositoryRepoAppDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryRepoAppDetailsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Directory) {
		toSerialize["directory"] = o.Directory
	}
	if !isNil(o.Helm) {
		toSerialize["helm"] = o.Helm
	}
	if !isNil(o.Kustomize) {
		toSerialize["kustomize"] = o.Kustomize
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableRepositoryRepoAppDetailsResponse struct {
	value *RepositoryRepoAppDetailsResponse
	isSet bool
}

func (v NullableRepositoryRepoAppDetailsResponse) Get() *RepositoryRepoAppDetailsResponse {
	return v.value
}

func (v *NullableRepositoryRepoAppDetailsResponse) Set(val *RepositoryRepoAppDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryRepoAppDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryRepoAppDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryRepoAppDetailsResponse(val *RepositoryRepoAppDetailsResponse) *NullableRepositoryRepoAppDetailsResponse {
	return &NullableRepositoryRepoAppDetailsResponse{value: val, isSet: true}
}

func (v NullableRepositoryRepoAppDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryRepoAppDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
