/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the V1alpha1HostResourceInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1HostResourceInfo{}

// V1alpha1HostResourceInfo struct for V1alpha1HostResourceInfo
type V1alpha1HostResourceInfo struct {
	Capacity             *string `json:"capacity,omitempty"`
	RequestedByApp       *string `json:"requestedByApp,omitempty"`
	RequestedByNeighbors *string `json:"requestedByNeighbors,omitempty"`
	ResourceName         *string `json:"resourceName,omitempty"`
}

// NewV1alpha1HostResourceInfo instantiates a new V1alpha1HostResourceInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1HostResourceInfo() *V1alpha1HostResourceInfo {
	this := V1alpha1HostResourceInfo{}
	return &this
}

// NewV1alpha1HostResourceInfoWithDefaults instantiates a new V1alpha1HostResourceInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1HostResourceInfoWithDefaults() *V1alpha1HostResourceInfo {
	this := V1alpha1HostResourceInfo{}
	return &this
}

// GetCapacity returns the Capacity field value if set, zero value otherwise.
func (o *V1alpha1HostResourceInfo) GetCapacity() string {
	if o == nil || isNil(o.Capacity) {
		var ret string
		return ret
	}
	return *o.Capacity
}

// GetCapacityOk returns a tuple with the Capacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1HostResourceInfo) GetCapacityOk() (*string, bool) {
	if o == nil || isNil(o.Capacity) {
		return nil, false
	}
	return o.Capacity, true
}

// HasCapacity returns a boolean if a field has been set.
func (o *V1alpha1HostResourceInfo) HasCapacity() bool {
	if o != nil && !isNil(o.Capacity) {
		return true
	}

	return false
}

// SetCapacity gets a reference to the given string and assigns it to the Capacity field.
func (o *V1alpha1HostResourceInfo) SetCapacity(v string) {
	o.Capacity = &v
}

// GetRequestedByApp returns the RequestedByApp field value if set, zero value otherwise.
func (o *V1alpha1HostResourceInfo) GetRequestedByApp() string {
	if o == nil || isNil(o.RequestedByApp) {
		var ret string
		return ret
	}
	return *o.RequestedByApp
}

// GetRequestedByAppOk returns a tuple with the RequestedByApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1HostResourceInfo) GetRequestedByAppOk() (*string, bool) {
	if o == nil || isNil(o.RequestedByApp) {
		return nil, false
	}
	return o.RequestedByApp, true
}

// HasRequestedByApp returns a boolean if a field has been set.
func (o *V1alpha1HostResourceInfo) HasRequestedByApp() bool {
	if o != nil && !isNil(o.RequestedByApp) {
		return true
	}

	return false
}

// SetRequestedByApp gets a reference to the given string and assigns it to the RequestedByApp field.
func (o *V1alpha1HostResourceInfo) SetRequestedByApp(v string) {
	o.RequestedByApp = &v
}

// GetRequestedByNeighbors returns the RequestedByNeighbors field value if set, zero value otherwise.
func (o *V1alpha1HostResourceInfo) GetRequestedByNeighbors() string {
	if o == nil || isNil(o.RequestedByNeighbors) {
		var ret string
		return ret
	}
	return *o.RequestedByNeighbors
}

// GetRequestedByNeighborsOk returns a tuple with the RequestedByNeighbors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1HostResourceInfo) GetRequestedByNeighborsOk() (*string, bool) {
	if o == nil || isNil(o.RequestedByNeighbors) {
		return nil, false
	}
	return o.RequestedByNeighbors, true
}

// HasRequestedByNeighbors returns a boolean if a field has been set.
func (o *V1alpha1HostResourceInfo) HasRequestedByNeighbors() bool {
	if o != nil && !isNil(o.RequestedByNeighbors) {
		return true
	}

	return false
}

// SetRequestedByNeighbors gets a reference to the given string and assigns it to the RequestedByNeighbors field.
func (o *V1alpha1HostResourceInfo) SetRequestedByNeighbors(v string) {
	o.RequestedByNeighbors = &v
}

// GetResourceName returns the ResourceName field value if set, zero value otherwise.
func (o *V1alpha1HostResourceInfo) GetResourceName() string {
	if o == nil || isNil(o.ResourceName) {
		var ret string
		return ret
	}
	return *o.ResourceName
}

// GetResourceNameOk returns a tuple with the ResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1HostResourceInfo) GetResourceNameOk() (*string, bool) {
	if o == nil || isNil(o.ResourceName) {
		return nil, false
	}
	return o.ResourceName, true
}

// HasResourceName returns a boolean if a field has been set.
func (o *V1alpha1HostResourceInfo) HasResourceName() bool {
	if o != nil && !isNil(o.ResourceName) {
		return true
	}

	return false
}

// SetResourceName gets a reference to the given string and assigns it to the ResourceName field.
func (o *V1alpha1HostResourceInfo) SetResourceName(v string) {
	o.ResourceName = &v
}

func (o V1alpha1HostResourceInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1HostResourceInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Capacity) {
		toSerialize["capacity"] = o.Capacity
	}
	if !isNil(o.RequestedByApp) {
		toSerialize["requestedByApp"] = o.RequestedByApp
	}
	if !isNil(o.RequestedByNeighbors) {
		toSerialize["requestedByNeighbors"] = o.RequestedByNeighbors
	}
	if !isNil(o.ResourceName) {
		toSerialize["resourceName"] = o.ResourceName
	}
	return toSerialize, nil
}

type NullableV1alpha1HostResourceInfo struct {
	value *V1alpha1HostResourceInfo
	isSet bool
}

func (v NullableV1alpha1HostResourceInfo) Get() *V1alpha1HostResourceInfo {
	return v.value
}

func (v *NullableV1alpha1HostResourceInfo) Set(val *V1alpha1HostResourceInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1HostResourceInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1HostResourceInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1HostResourceInfo(val *V1alpha1HostResourceInfo) *NullableV1alpha1HostResourceInfo {
	return &NullableV1alpha1HostResourceInfo{value: val, isSet: true}
}

func (v NullableV1alpha1HostResourceInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1HostResourceInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
