name: Unikorn Push
on:
  push:
    branches-ignore:
    - main
    tags-ignore:
    - '*'
env:
  GO_VERSION: 1.19.1
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Golang CI/Helm Lint
      run: make lint
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Unit Test
      run: make test
